FROM deeppavlov/base-cpu:0.3.0

RUN mkdir dp-agent
WORKDIR /dp-agent
COPY . /dp-agent/.

ENV PYTHONPATH "${PYTONPATH}:/dp-agent"

RUN python3.6 -m deeppavlov install legacy_components/skills/ranking_chitchat/agent_ranking_chitchat_2staged_tfidf_smn_v4_prep.json && \
    python3.6 -m deeppavlov install legacy_components/skill_selectors/chitchat_odqa_selector/sselector_chitchat_odqa.json

CMD python3.6 -m legacy_components.core.run_dp_servers $CONFIG -p 5000 -host 0.0.0.0 -ep skill