FROM deeppavlov/base:latest

ARG skillconfig
ARG skillport
ARG gpu

ENV CONFIG=$skillconfig
ENV PORT=$skillport
ENV GPU=$gpu

RUN mkdir dp-agent
WORKDIR /dp-agent
COPY . /dp-agent/.
ENV PYTHONPATH "${PYTONPATH}:/dp-agent"

RUN if [ $GPU = "true" ]; then pip install -r /base/DeepPavlov/deeppavlov/requirements/tf-gpu.txt; fi
RUN python3.6 -m deeppavlov install $CONFIG

ENTRYPOINT python3.6 -m core.run_dp_servers $CONFIG -p $PORT