FROM python:3.6-slim-stretch

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y --fix-missing && \
    apt-get install -y -q \
        build-essential \
        openssl \
        git \
        libssl-dev \
        libffi-dev && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONIOENCODING=utf-8

COPY requirements.txt /
RUN pip3 install --no-cache-dir -r requirements.txt

RUN mkdir dp-agent
WORKDIR /dp-agent
COPY . /dp-agent/.

ENV PYTHONPATH "${PYTONPATH}:/dp-agent"

EXPOSE 8888
