# Commented lines refer to python objects

agent:
  channel: cmd
  debug: false
#  state_manager_class: StateManager
#  workflow_manager_class: WorkflowManager
#  db_class: DataBase
  pipeline_config: pipeline_conf.json
  db_config: db_conf.json
  overwrite_last_chance: null
  overwrite_timeout: null
  formatters_module: null
  connectors_module: null
  response_logger: true
  response_time_limit: 0
#  output_formatter: http_api_output_formatter
#  debug_output_formatter: http_debug_output_formatter
  port: 4242
  cors: false
  telegram_token: ""
  telegram_proxy: ""

hydra:
  run:
    dir: .
  output_subdir: null
