agent:
  channel: cmd
  debug: false
  state_manager_class: core.state_manager.StateManager
  workflow_manager_class: core.workflow_manager.WorkflowManager
  db_class: core.db.DataBase
  pipeline_config: pipeline_conf.json
  db_config: db_conf.json
  overwrite_last_chance: null
  overwrite_timeout: null
  formatters_module: null
  connectors_module: null
  enable_response_logger: true
  response_time_limit: 0
  output_formatter: state_formatters.output_formatters.http_api_output_formatter
  debug_output_formatter: state_formatters.output_formatters.http_debug_output_formatter
  port: 4242
  cors: false
  telegram_token: ""
  telegram_proxy: ""

hydra:
  run:
    dir: .
  output_subdir: null
