ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG SERVICE_CONFIG
ARG SERVICE_PORT

ENV CONFIG=$SERVICE_CONFIG
ENV PORT=$SERVICE_PORT
ENV TFHUB_CACHE_DIR=/tmp/tfhub

VOLUME /tmp/tfhub

WORKDIR dp-agent

COPY . /base/dp-agent

RUN python -m deeppavlov install $CONFIG && \
    sed -i "/uvicorn.run/s/app,/app, timeout_keep_alive=20,/g" "/base/DeepPavlov/deeppavlov/utils/server/server.py"

CMD python -m deeppavlov riseapi $CONFIG -p $PORT -d